parameters:
    database_driver: pdo_mysql
    database_host: mysql2.unifr.ch
    database_port: ~
    database_name: 10477_callisto
    database_user: 10477_callisto
    database_password: WjZP2A4QM4WE?WmZ
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~
    locale: fr
    secret: '***REMOVED***'
